services:
  dev-env:
    container_name: dev-env
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspace:cached
    cap_add:
      - CAP_IPC_LOCK
    command: /bin/sh -c "while sleep 1000; do :; done"
    depends_on:
      - mongodb
    ports:
      - '4000:4000'
  mongodb:
    container_name: mongodb
    image: bitnami/mongodb:latest
    ports:
      - '27017:27017'
    environment:
      - MONGODB_ROOT_USER=root
      - MONGODB_ROOT_PASSWORD=example
    volumes:
      - mongodb_data:/bitnami/mongodb

volumes:
  mongodb_data:
    driver: local