services:
  demo-graphql-dev-env:
    container_name: demo-graphql-dev-env
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspace:cached
    cap_add:
      - CAP_IPC_LOCK
    command: /bin/sh -c "while sleep 1000; do :; done"
    depends_on:
      - demo-graphql-mongodb
    ports:
      - '4000:4000'
  demo-graphql-mongodb:
    container_name: demo-graphql-mongodb
    image: bitnami/mongodb:latest
    ports:
      - '37017:27017'
    environment:
      - MONGODB_ROOT_USER=root
      - MONGODB_ROOT_PASSWORD=example
    volumes:
      - demo-graphql-mongodb-data:/bitnami/mongodb

volumes:
  demo-graphql-mongodb-data:
    driver: local
